# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 我的作品
email: chiayig@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  我的開發作品
baseurl: "/MyExperience" # the subpath of your site, e.g. /blog
url: "https://peterokay.github,io" # the base hostname & protocol for your site
twitter_username: 
github_username:  peterokay

# Build settings
markdown: kramdown
theme: minima

sections:
  - title: '關於我'    
    id: 'about_me'

  - title: '氣象小叮嚀(Web+Line)'
    id: 'weather'
    
  - title: '物品管理(APP)'
    id: 'thing'

  - title: 'TellMe你說我聽(Web+Hybrid APP)'
    id: 'tellme'

  - title: 'ITree互助平台(Web)'
    id: 'itree'



exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - Gruntfile.js
  - node_modules  
